In [3]:
%load_ext autoreload
%autoreload 2

import torch
import torch.nn as nn

In [7]:
a = nn.functional.normalize(torch.rand(5, 8), dim=1)

a

tensor([[0.1531, 0.2635, 0.4024, 0.4633, 0.3186, 0.4551, 0.4638, 0.0835],
        [0.1392, 0.4005, 0.0702, 0.5426, 0.5568, 0.3502, 0.2161, 0.2036],
        [0.4334, 0.3428, 0.4093, 0.5532, 0.0529, 0.1622, 0.3688, 0.2364],
        [0.4908, 0.5195, 0.0566, 0.2100, 0.4331, 0.2564, 0.3644, 0.2362],
        [0.3070, 0.0146, 0.5998, 0.0007, 0.3331, 0.3968, 0.0861, 0.5196]])

In [22]:
d_model = 8
d_head = 4

W = nn.Linear(d_model, d_head, bias=True)

In [28]:
nn.functional.normalize(W.weight.data, dim=1)

tensor([[ 0.3099,  0.2017, -0.3154, -0.3220, -0.4352, -0.5511,  0.3520, -0.2075],
        [-0.4646,  0.0176,  0.3620, -0.0090,  0.6122, -0.1070,  0.2112, -0.4711],
        [-0.1046,  0.5039,  0.1310, -0.0678, -0.0075,  0.4254,  0.5461, -0.4839],
        [-0.4674, -0.3934,  0.1226, -0.0053,  0.0143,  0.5657,  0.5386,  0.0382]])

tensor([0.5702, 0.5739, 0.5974, 0.6178])

In [10]:
a.norm(dim=0)

tensor([0.7522, 0.7858, 0.8351, 0.9270, 0.8443, 0.7611, 0.7335, 0.6558])

In [ ]:
from omni.preprocessing.tokenizer import AutoTokenizer

tokenizer = AutoTokenizer.create("EleutherAI/gpt-neo-125m")
tokenizer.add_special_tokens({"pad_token": "<pad>"})

In [ ]:
def causal_attention_mask(sequence_length: int, dtype=torch.float32):
    mask = torch.triu(torch.ones((1, 1, sequence_length, sequence_length), dtype=dtype), diagonal=1)
    mask = mask.masked_fill(mask == 1, float("-inf")) 
    return mask

mask = causal_attention_mask(5)

In [ ]:
mask

In [ ]:
from datasets import load_from_disk

ds = load_from_disk("data/pretokenized_fineweb-edu-2BT")

In [ ]:
tokenizer.pad_token_id

In [ ]:
(x == 50257).sum()

In [ ]:
for i in range(0, 15):

    print(tokenizer.decode(ds[i]["input_ids"]))

In [ ]:
import torch

from omni.architectures.llama import LlamaConfig
from omni.modules.transformer import Transformer
from omni.preprocessing.tokenizer import AutoTokenizer
from omni.utils.system import auto_device

tokenizer = AutoTokenizer.create("EleutherAI/gpt-neo-125m")
tokenizer.add_special_tokens({"pad_token": "<pad>"})

llama_config = LlamaConfig(
    vocab_size=50258,
    seq_len=512,
    d_model=256,
    num_heads=8,
    num_kv_heads=8,
    num_layers=4,
    rope_theta=0.1,
    norm_eps=1e-6,
    activation_fn="silu",
    mlp_bias=False,
    mlp_dropout=0.0,
    attention_bias=False,
    attention_dropout=0.0,
    pos_encoding_type="rope",
    mlp="mlp_swiglu",
    normalization="rmsnorm",
    attention="gqa",
)

model = Transformer(llama_config)

## create KV cache

checkpoint = torch.load("checkpoints/llama-30M_20250123_104138/init.ckpt", weights_only=True)
model.load_state_dict(checkpoint["model"])

device="mps"
model = model.to(device)
model.eval()

In [ ]:
device="mps"
prompt = "Once upon a time"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)

In [ ]:
outputs = model(input_ids)
next_token_logits = outputs[:, -1, :]

In [ ]:
top_k_values, top_k_indices = torch.topk(logits, self.top_k, dim=-1)

In [ ]:
top_k_values = torch.tensor([float("-inf"), 1.0, 2.0])

top_k_values
nn.functional.softmax(top_k_values, dim=-1)

In [ ]:
float("-inf")

In [ ]:
sorted_logits, sorted_indices = torch.sort(
    top_k_values, dim=-1, descending=True
)
cumulative_probs = torch.cumsum(
    nn.functional.softmax(sorted_logits, dim=-1), dim=-1
)

In [ ]:
next_token_logits

In [ ]:
visualize_logit_distribution(next_token_logits[0], top_k=500)

In [ ]:
import torch
import matplotlib.pyplot as plt

def visualize_logit_distribution(logits, top_k=500):
    """
    Visualizes the logit distribution by focusing on the top-k logits.

    Args:
        logits (torch.Tensor): Logits tensor of shape (vocab_size,).
        top_k (int): Number of top logits to visualize. Defaults to 500.
    """
    if logits.dim() != 1:
        raise ValueError("Logits tensor must be 1-dimensional (vocab_size,).")

    # Convert logits to probabilities and take log
    log_probs = torch.log_softmax(logits, dim=0)

    # Get the top-k log probabilities and their indices
    top_log_probs, top_indices = torch.topk(log_probs, k=top_k)

    # Sort the top-k log probabilities for visualization
    sorted_log_probs, sorted_indices = torch.sort(top_log_probs, descending=True)

    # Plot the distribution
    plt.figure(figsize=(10, 6))
    plt.plot(sorted_log_probs.detach().cpu().numpy(), marker="o", linestyle="-")
    plt.title(f"Log Probability Distribution (Top {top_k})", fontsize=14)
    plt.xlabel("Rank", fontsize=12)
    plt.ylabel("Log Probability Value", fontsize=12)
    plt.grid(alpha=0.5)
    plt.show()


In [ ]:
import tokenizers.processors as processors

def _add_bos_token(tokenizer: AutoTokenizer):
    tokenizer._tokenizer.post_processor = processors.Sequence(
        [
            processors.ByteLevel(trim_offsets=False),
            processors.TemplateProcessing(
                single=f"{tokenizer.bos_token}:0 $A:0",
                pair=f"{tokenizer.bos_token}:0 $A:0 {tokenizer.bos_token}:1 $B:1",
                special_tokens=[
                    (tokenizer.bos_token, tokenizer.bos_token_id),
                ],
            ),
        ]
    )
    return tokenizer

In [ ]:
tokenizer2 = _add_bos_token(tokenizer) 

In [ ]:
torch.log(torch.tensor(50000))

In [ ]:
test = "thjis is a test, this is a test"

output = tokenizer2(test, padding="max_length", max_length=3, truncation=True, return_overflowing_tokens=True)

In [ ]:
d_model=128
hidden_dim = 4 * int(2 * d_model / 3)
hidden_dim = 4 * (
    (hidden_dim + 4 - 1) // 4
)

hidden_dim

In [ ]:
import torch

logits = torch.tensor([1,5,10], dtype=torch.float32)
torch.softmax(logits, dim=0)

In [ ]:
tokenizer.special_tokens_map

In [ ]:
tokenizer.encode(x, padding="max_length", max_length=max_length, truncation=True, return_overflowing_tokens=True)

In [ ]:
tokenizer(test, )

In [ ]:
output

In [ ]:
from omni.modules.pos_embeddings import precompute_freqs_cis_real

pos_embeddings = precompute_freqs_cis_real(64, 512)

In [ ]:
def _tokenize(dataset, tokenizer: AutoTokenizer, num_proc):
    print("Tokenizing dataset...")
    dataset = dataset.map(
        lambda x: tokenizer(
            x["text"],
            truncation=True,
            max_length=512,
            padding="max_length",
            return_overflowing_tokens=True,
        ),
        batched=True,
        num_proc=num_proc,
        remove_columns=dataset.column_names,
    )
    dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])
    return dataset

In [ ]:
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories", split="train", num_proc=1)

In [ ]:
_tokenize(ds, tokenizer, 2)